# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(463, 385)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("background-color: rgb(28, 31, 70);\n"
"\n"
"QLabel{\n"
"    color: #fff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.city = QtWidgets.QLineEdit(self.centralwidget)
        self.city.setGeometry(QtCore.QRect(100, 80, 241, 51))
        self.city.setStyleSheet("color: #fff;\n"
"font-size: 24px;\n"
"text-align: center;")
        self.city.setAlignment(QtCore.Qt.AlignCenter)
        self.city.setObjectName("city")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 161, 41))
        self.label.setStyleSheet("color: #fff;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 150, 461, 231))
        self.tabWidget.setStyleSheet("color: #000;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 1, 1, 1)
        self.todayPressure = QtWidgets.QLabel(self.gridLayoutWidget)
        self.todayPressure.setStyleSheet("border-top: 1px solid #fff;\n"
"color: #fff;")
        self.todayPressure.setText("")
        self.todayPressure.setAlignment(QtCore.Qt.AlignCenter)
        self.todayPressure.setObjectName("todayPressure")
        self.gridLayout.addWidget(self.todayPressure, 7, 2, 1, 1)
        self.todayTemp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.todayTemp.setStyleSheet("border-top: 1px solid #fff;\n"
"color: #fff;")
        self.todayTemp.setText("")
        self.todayTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.todayTemp.setObjectName("todayTemp")
        self.gridLayout.addWidget(self.todayTemp, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("border-top: 1px solid #fff;\n"
"color: #fff;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("border-top: 1px solid #fff;\n"
"color: #fff;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.todayHumidity = QtWidgets.QLabel(self.gridLayoutWidget)
        self.todayHumidity.setStyleSheet("border-top: 1px solid #fff;\n"
"color: #fff;")
        self.todayHumidity.setText("")
        self.todayHumidity.setAlignment(QtCore.Qt.AlignCenter)
        self.todayHumidity.setObjectName("todayHumidity")
        self.gridLayout.addWidget(self.todayHumidity, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("border-top: 1px solid #fff;\n"
"color: #fff;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 1, 1, 1)
        self.todayImg = QtWidgets.QLabel(self.gridLayoutWidget)
        self.todayImg.setText("")
        self.todayImg.setPixmap(QtGui.QPixmap("images/Погода.jpg"))
        self.todayImg.setAlignment(QtCore.Qt.AlignCenter)
        self.todayImg.setObjectName("todayImg")
        self.gridLayout.addWidget(self.todayImg, 1, 0, 2, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 461, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.humidity_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.humidity_1.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.humidity_1.setText("")
        self.humidity_1.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_1.setObjectName("humidity_1")
        self.gridLayout_2.addWidget(self.humidity_1, 4, 1, 1, 1)
        self.pressure_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pressure_2.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.pressure_2.setText("")
        self.pressure_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_2.setObjectName("pressure_2")
        self.gridLayout_2.addWidget(self.pressure_2, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 7, 0, 1, 1)
        self.pressure_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pressure_1.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.pressure_1.setText("")
        self.pressure_1.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_1.setObjectName("pressure_1")
        self.gridLayout_2.addWidget(self.pressure_1, 7, 1, 1, 1)
        self.temp_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.temp_2.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.temp_2.setText("")
        self.temp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_2.setObjectName("temp_2")
        self.gridLayout_2.addWidget(self.temp_2, 3, 2, 1, 1)
        self.temp_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.temp_1.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.temp_1.setText("")
        self.temp_1.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_1.setObjectName("temp_1")
        self.gridLayout_2.addWidget(self.temp_1, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.pressure_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pressure_3.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.pressure_3.setText("")
        self.pressure_3.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_3.setObjectName("pressure_3")
        self.gridLayout_2.addWidget(self.pressure_3, 7, 3, 1, 1)
        self.temp_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.temp_3.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.temp_3.setText("")
        self.temp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_3.setObjectName("temp_3")
        self.gridLayout_2.addWidget(self.temp_3, 3, 3, 1, 1)
        self.temp_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.temp_5.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.temp_5.setText("")
        self.temp_5.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_5.setObjectName("temp_5")
        self.gridLayout_2.addWidget(self.temp_5, 3, 5, 1, 1)
        self.temp_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.temp_4.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.temp_4.setText("")
        self.temp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_4.setObjectName("temp_4")
        self.gridLayout_2.addWidget(self.temp_4, 3, 4, 1, 1)
        self.humidity_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.humidity_5.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.humidity_5.setText("")
        self.humidity_5.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_5.setObjectName("humidity_5")
        self.gridLayout_2.addWidget(self.humidity_5, 4, 5, 1, 1)
        self.pressure_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pressure_4.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.pressure_4.setText("")
        self.pressure_4.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_4.setObjectName("pressure_4")
        self.gridLayout_2.addWidget(self.pressure_4, 7, 4, 1, 1)
        self.pressure_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pressure_5.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.pressure_5.setText("")
        self.pressure_5.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_5.setObjectName("pressure_5")
        self.gridLayout_2.addWidget(self.pressure_5, 7, 5, 1, 1)
        self.humidity_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.humidity_4.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.humidity_4.setText("")
        self.humidity_4.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_4.setObjectName("humidity_4")
        self.gridLayout_2.addWidget(self.humidity_4, 4, 4, 1, 1)
        self.img_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img_3.setText("")
        self.img_3.setPixmap(QtGui.QPixmap("images/Погода.jpg"))
        self.img_3.setObjectName("img_3")
        self.gridLayout_2.addWidget(self.img_3, 1, 3, 2, 1)
        self.img_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img_4.setText("")
        self.img_4.setPixmap(QtGui.QPixmap("images/Погода.jpg"))
        self.img_4.setScaledContents(False)
        self.img_4.setObjectName("img_4")
        self.gridLayout_2.addWidget(self.img_4, 1, 4, 2, 1)
        self.img_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img_2.setText("")
        self.img_2.setPixmap(QtGui.QPixmap("images/Погода.jpg"))
        self.img_2.setObjectName("img_2")
        self.gridLayout_2.addWidget(self.img_2, 1, 2, 2, 1)
        self.img_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img_5.setText("")
        self.img_5.setPixmap(QtGui.QPixmap("images/Погода.jpg"))
        self.img_5.setScaledContents(False)
        self.img_5.setObjectName("img_5")
        self.gridLayout_2.addWidget(self.img_5, 1, 5, 2, 1)
        self.humidity_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.humidity_2.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.humidity_2.setText("")
        self.humidity_2.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_2.setObjectName("humidity_2")
        self.gridLayout_2.addWidget(self.humidity_2, 4, 2, 1, 1)
        self.humidity_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.humidity_3.setStyleSheet("color: #fff;\n"
"border-top: 1px solid #fff;")
        self.humidity_3.setText("")
        self.humidity_3.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_3.setObjectName("humidity_3")
        self.gridLayout_2.addWidget(self.humidity_3, 4, 3, 1, 1)
        self.img_1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.img_1.setStyleSheet("color: #fff;")
        self.img_1.setText("")
        self.img_1.setPixmap(QtGui.QPixmap("images/Погода.jpg"))
        self.img_1.setAlignment(QtCore.Qt.AlignCenter)
        self.img_1.setObjectName("img_1")
        self.gridLayout_2.addWidget(self.img_1, 1, 1, 2, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.loadLabel = QtWidgets.QLabel('Loading', self.centralwidget)
        self.loadLabel.move(0, 0)
        self.loadLabel.resize(self.size())
        self.loadLabel.setAlignment(QtCore.Qt.AlignCenter)
        movie = QtGui.QMovie('./images/loader.gif')
        movie.start()
        self.loadLabel.setMovie(movie)
        self.loadLabel.setStyleSheet("background-color: rgba(255, 255, 255, .7);")
        self.loadLabel.hide()

        self.tabWidget.setCurrentIndex(0)

        self.todayImg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.todayImg.setToolTip('Weather')

        for i in range(1, 6):
                getattr(self, f"img_{i}").setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                getattr(self, f"img_{i}").setToolTip('Weather')

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather App"))
        self.label.setText(_translate("MainWindow", "Введите город"))
        self.label_3.setText(_translate("MainWindow", "Давление"))
        self.label_4.setText(_translate("MainWindow", "Температура"))
        self.label_7.setText(_translate("MainWindow", "Влажность"))
        self.todayImg.setStyleSheet(_translate("MainWindow", "border-top: 1px solid #fff;\n"
"color: #fff;"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Сегодня"))
        self.gridLayoutWidget_2.setStyleSheet(_translate("MainWindow", "color: #fff;\n"
"border-top: 1px solid #fff;"))
        self.label_12.setText(_translate("MainWindow", "Влажность"))
        self.label_11.setText(_translate("MainWindow", "Давление"))
        self.label_13.setText(_translate("MainWindow", "Температура"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "На 5 дней"))
